# fly.toml app configuration file generated for fly-pr-preview-example on 2023-12-01T12:06:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-pr-preview-example"
primary_region = "waw"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
